### ISSUE TITLE
Add Type Hints to TTR module

### ISSUE THREAD

**Issue by dpalmasan** [dpalmasan/TRUNAJOD2.0#18]
TTR module can be found here:

https://github.com/dpalmasan/TRUNAJOD2.0/blob/master/src/TRUNAJOD/ttr.py

For example, using type hints we could define:

```python
def type_token_ratio(word_list):
```

as

```python
def type_token_ratio(word_list: List[str]) -> float:
```

**Comment by sourvad** [comment]
@dpalmasan Can I work on this issue?

**Comment by dpalmasan** [comment]
@sourvad sure! Feel free to work on this issue

**Comment by sourvad** [comment]
Hello @dpalmasan ,there is no docstring for the following parameters:

1. In lexical_diversity_mtld:
     - model_name
     - ttr_segment

2. In one_side_lexical_diversity_mtld:
     - model_name

Should type hints be added for these parameters as well, or is it abstracted away by design?

**Comment by dpalmasan** [comment]
Good catch! @sourvad Probably we need to also update the docstrings

**Comment by sourvad** [comment]
Gotcha, will do.

**Comment by sourvad** [comment]
@dpalmasan I believe it's done. Build passed and ran pre-commit.

**Comment by dpalmasan** [comment]
PR merged, closing.
