### ISSUE TITLE
Add type hints to syllabizer

### ISSUE THREAD

**Issue by dpalmasan** [dpalmasan/TRUNAJOD2.0#37]
Add type hints to `src/syllabizer.py`

**Comment by supersonic1999** [comment]
Hi, I added type hints to this files and 3 others. Haven't used GitHub in years, hope i pushed it correctly..

**Comment by dpalmasan** [comment]
Hello! Thanks for taking this, I already added some comments in the PR!

**Comment by dpalmasan** [comment]
The PR was merged, closing!
