### ISSUE TITLE
Paper grammar review

### ISSUE THREAD

**Issue by mbdemoraes** [dpalmasan/TRUNAJOD2.0#40]
There are some grammar issues on the paper. For instance, using "have" instead of "has", missing articles (such as "the" text), missing hyphen (such as grid-based), among others. I suggest using Grammarly (https://app.grammarly.com/) to assist the authors on this task.

cc https://github.com/openjournals/joss-reviews/issues/3153

**Comment by dpalmasan** [comment]
Hello @mbdemoraes Thanks for the detailed review! I have updated the `paper.md` file, and used Grammarly as suggested (I wasn't aware that it had a free version, it is very useful). I already committed the changes, so let me know should I change anything else in the `paper.md`, I will also regenerate the paper in the JOSS review

**Comment by mbdemoraes** [comment]
@dpalmasan I'm glad to know that Grammarly helped! For us, non-native English speakers, English grammar can be quite challenging. I've checked and everything is ok now. I'm going to close the issue.
