### ISSUE TITLE
Missing community guidelines

### ISSUE THREAD

**Issue by mbdemoraes** [dpalmasan/TRUNAJOD2.0#41]
Both the documentation page and the README file should contain clear guidelines for third parties who wish to contribute to the software, report issues, or seek support. Here is an example:

If you wish to contribute to the software, report issues or problems, or seek support, feel free to use the issue report of this repository or to contact us.

Author's 1 name - author1@email.com
 Author's 2 name - author2@email.com

**Comment by dpalmasan** [comment]
Updated `README.md` to include community guidelines. Let me know if anything is missing! Thanks for the review!

**Comment by mbdemoraes** [comment]
Community guidelines checked! I'm going to close the issue now.
