### ISSUE TITLE
State of the field

### ISSUE THREAD

**Issue by mbdemoraes** [dpalmasan/TRUNAJOD2.0#50]
In terms of state of the field, the paper include a lot of discussions around text measurements. But how about competitor libraries? TRUNAJOD is the only library/package (including other programming languages) that serves this purpose? If it isn't the only one,  how does it works compared to those implementations? 

cc https://github.com/openjournals/joss-reviews/issues/3153

**Comment by dpalmasan** [comment]
Okay, it seems I need to update the `paper.md` with such discussion. Thanks for pointing out! I will let you know once I fix this!

**Comment by dpalmasan** [comment]
@mbdemoraes I updated the `paper.md` file to provide more details for the comparisons with other libs. Let me know if anything is missing. I will re-generate the paper on JOSS site.

**Comment by mbdemoraes** [comment]
@dpalmasan well done! Everything is fine now.
