### ISSUE TITLE
Include additional examples on the documentation

### ISSUE THREAD

**Issue by mbdemoraes** [dpalmasan/TRUNAJOD2.0#51]
In the documentation, there is only one example of usage. Since there is a lot of features, the authors should include at least two or three more examples, using other features to improve the understanding of the proposed package. Currently, the remaining functionality is described only at an API level, which seems insufficient.

cc https://github.com/openjournals/joss-reviews/issues/3153

**Comment by dpalmasan** [comment]
Got it. I will include a more detailed example of usage. I will let you know when this is done!

**Comment by dpalmasan** [comment]
@mbdemoraes I included a code snippet showing how this can be used on research related to text analysis. I also provided a real application demo (as a youtube video) built on `TRUNAJOD`. Let me know if I need to improve anything else. Thanks for the review BTW!

**Comment by mbdemoraes** [comment]
@dpalmasan I've checked the new examples, thank you for including them. By the way, very good video!

Since the modification addressed the suggestion, I'm going to close the issue now.
